/**
 * A QR encoder, written rather than installed.
 *
 * `vite-plugin-singlefile` base64-inlines every asset into `index.html`, which is
 * then embedded in the daemon binary — so a dependency here is permanent bytes in
 * every veld release, for one panel. This covers exactly what that panel needs and
 * nothing else: **byte mode, error level M, versions 1–10**. Anything longer than that
 * returns `null` and the caller keeps showing the link.
 *
 * Scope, stated so the next person does not go looking for the general case:
 *
 * - **Byte mode only.** A URL is not alphanumeric-mode material (the mode's charset
 *   has no lowercase letters), so the numeric and alphanumeric modes would never be
 *   selected for the one payload this encodes. Kanji mode likewise.
 * - **Error level M** (~15% recovery), the level essentially every URL QR uses. L
 *   would buy ~20% more capacity we do not need; Q and H shrink capacity for a code
 *   that is being scanned off a bright screen from 20cm away.
 * - **Versions 1–10**, i.e. up to 214 payload bytes. A gateway URL with a password
 *   fragment is ~120. Beyond that the honest answer is "too long to scan", not a
 *   53×53 grid of 1px modules on a phone screen.
 *
 * Correctness is pinned by `qr.test.ts`, which compares whole matrices against
 * fixtures generated by the `qrcode` PyPI package plus a from-the-spec mask scorer (see
 * `qrFixtures.ts` — `segno` was tried first and turned out to emit a spurious pad
 * codeword) — including a case per version boundary and one per mask. That is the only
 * kind of test worth having here: an encoder that is subtly wrong still renders a
 * plausible square, and no amount of reading the code tells you a scanner can read it.
 *
 * Pure and DOM-free on purpose, like the rest of `shared/` — `vitest` runs with
 * `environment: "node"`.
 */

/** Payload capacity in bytes at error level M, indexed by version − 1. */
const MAX_BYTES_M = [14, 26, 42, 62, 84, 106, 122, 152, 180, 213] as const;

/**
 * Per-version block structure at error level M.
 *
 * `groups` is `[blockCount, dataCodewordsPerBlock]` pairs, in the order the spec
 * lists them — group 2's blocks are one codeword longer than group 1's, which is
 * what makes the interleave at the end non-trivial. Transcribed from ISO/IEC
 * 18004 table 9 via `segno`'s tables rather than typed from memory, and pinned by
 * the fixture tests: a wrong `ecPerBlock` here produces a scannable-looking code
 * that no scanner accepts.
 */
interface VersionSpec {
  /** Total codewords (data + error correction) in the symbol. */
  total: number;
  /** Error-correction codewords per block. Uniform across groups by construction. */
  ecPerBlock: number;
  groups: readonly (readonly [number, number])[];
  /** Alignment-pattern centre coordinates, empty for version 1. */
  align: readonly number[];
}

const VERSIONS: readonly VersionSpec[] = [
  { total: 26, ecPerBlock: 10, groups: [[1, 16]], align: [] },
  { total: 44, ecPerBlock: 16, groups: [[1, 28]], align: [6, 18] },
  { total: 70, ecPerBlock: 26, groups: [[1, 44]], align: [6, 22] },
  { total: 100, ecPerBlock: 18, groups: [[2, 32]], align: [6, 26] },
  { total: 134, ecPerBlock: 24, groups: [[2, 43]], align: [6, 30] },
  { total: 172, ecPerBlock: 16, groups: [[4, 27]], align: [6, 34] },
  { total: 196, ecPerBlock: 18, groups: [[4, 31]], align: [6, 22, 38] },
  { total: 242, ecPerBlock: 22, groups: [[2, 38], [2, 39]], align: [6, 24, 42] },
  { total: 292, ecPerBlock: 22, groups: [[3, 36], [2, 37]], align: [6, 26, 46] },
  { total: 346, ecPerBlock: 26, groups: [[4, 43], [1, 44]], align: [6, 28, 50] },
];

/** The error-level bits for M, as they appear in the format information. */
const ECC_BITS_M = 0b00;

// ---------------------------------------------------------------------------
// GF(256), the field the Reed–Solomon codewords live in.
// ---------------------------------------------------------------------------

/**
 * Log/antilog tables for GF(2^8) with the QR primitive polynomial
 * x^8 + x^4 + x^3 + x^2 + 1 (0x11d) and generator 2.
 */
const EXP = new Uint8Array(256);
const LOG = new Uint8Array(256);
{
  let x = 1;
  for (let i = 0; i < 255; i++) {
    EXP[i] = x;
    LOG[x] = i;
    x <<= 1;
    if (x & 0x100) x ^= 0x11d;
  }
  // EXP is cyclic with period 255; the 256th entry keeps `mul` branch-free for
  // exponents that sum to exactly 255.
  EXP[255] = EXP[0];
}

function mul(a: number, b: number): number {
  if (a === 0 || b === 0) return 0;
  return EXP[(LOG[a] + LOG[b]) % 255];
}

/** The generator polynomial for `n` error-correction codewords, low degree last. */
function generatorPoly(n: number): Uint8Array {
  let poly = new Uint8Array([1]);
  for (let i = 0; i < n; i++) {
    const next = new Uint8Array(poly.length + 1);
    // Multiply by (x - α^i); subtraction is XOR in this field.
    for (let j = 0; j < poly.length; j++) {
      next[j] ^= poly[j];
      next[j + 1] ^= mul(poly[j], EXP[i]);
    }
    poly = next;
  }
  return poly;
}

/** The `n` error-correction codewords for one data block. */
function ecCodewords(data: Uint8Array, n: number): Uint8Array {
  const gen = generatorPoly(n);
  const rem = new Uint8Array(n);
  for (const byte of data) {
    const factor = byte ^ rem[0];
    rem.copyWithin(0, 1);
    rem[n - 1] = 0;
    if (factor !== 0) {
      // gen[0] is 1, so the leading term cancels and only the tail contributes.
      for (let i = 0; i < n; i++) rem[i] ^= mul(gen[i + 1], factor);
    }
  }
  return rem;
}

// ---------------------------------------------------------------------------
// Bit stream → codewords
// ---------------------------------------------------------------------------

class Bits {
  readonly bits: number[] = [];
  push(value: number, length: number): void {
    for (let i = length - 1; i >= 0; i--) this.bits.push((value >>> i) & 1);
  }
}

/**
 * The data codewords for `bytes` at `version`, padded to the version's capacity.
 *
 * The pad sequence is the spec's: a 4-bit terminator (truncated if the capacity
 * ends first), zeroes to the next byte boundary, then `0xEC 0x11` alternating.
 */
function dataCodewords(bytes: Uint8Array, version: number): Uint8Array {
  const spec = VERSIONS[version - 1];
  const dataLen = spec.groups.reduce((n, [count, len]) => n + count * len, 0);
  const capacity = dataLen * 8;
  const bits = new Bits();
  bits.push(0b0100, 4); // byte mode
  // The character-count field widens at version 10 — a fixed 8 bits would silently
  // truncate a 300-byte payload's length on the versions that can hold it.
  bits.push(bytes.length, version < 10 ? 8 : 16);
  for (const b of bytes) bits.push(b, 8);
  for (let i = 0; i < 4 && bits.bits.length < capacity; i++) bits.bits.push(0);
  while (bits.bits.length % 8 !== 0) bits.bits.push(0);

  const out = new Uint8Array(dataLen);
  for (let i = 0; i < bits.bits.length; i += 8) {
    let byte = 0;
    for (let j = 0; j < 8; j++) byte = (byte << 1) | bits.bits[i + j];
    out[i / 8] = byte;
  }
  for (let i = bits.bits.length / 8, alt = 0; i < dataLen; i++, alt++) {
    out[i] = alt % 2 === 0 ? 0xec : 0x11;
  }
  return out;
}

/**
 * Interleave data and error-correction codewords into the final byte stream.
 *
 * Column-major across blocks, which is what makes a burst of damage spread across
 * every block instead of destroying one.
 */
function interleave(data: Uint8Array, version: number): Uint8Array {
  const spec = VERSIONS[version - 1];
  const blocks: { data: Uint8Array; ec: Uint8Array }[] = [];
  let offset = 0;
  for (const [count, len] of spec.groups) {
    for (let i = 0; i < count; i++) {
      const block = data.subarray(offset, offset + len);
      offset += len;
      blocks.push({ data: block, ec: ecCodewords(block, spec.ecPerBlock) });
    }
  }
  const out: number[] = [];
  const maxData = Math.max(...blocks.map((b) => b.data.length));
  for (let i = 0; i < maxData; i++) {
    for (const b of blocks) if (i < b.data.length) out.push(b.data[i]);
  }
  for (let i = 0; i < spec.ecPerBlock; i++) {
    for (const b of blocks) out.push(b.ec[i]);
  }
  return new Uint8Array(out);
}

// ---------------------------------------------------------------------------
// Matrix
// ---------------------------------------------------------------------------

/** A finished symbol: `modules[y][x]` is true for a dark module. */
export interface QrMatrix {
  version: number;
  /** Modules per side, excluding the quiet zone. */
  size: number;
  modules: boolean[][];
}

/** Working state: `null` marks a module no data bit may be written to. */
type Grid = (boolean | null)[][];

function blankGrid(size: number): Grid {
  return Array.from({ length: size }, () => Array<boolean | null>(size).fill(null));
}

function placeFinder(grid: Grid, cx: number, cy: number): void {
  // The 7×7 pattern plus its one-module separator, written as a distance rule so
  // the separator falls out of the same loop rather than needing its own bounds.
  for (let dy = -1; dy <= 7; dy++) {
    for (let dx = -1; dx <= 7; dx++) {
      const x = cx + dx;
      const y = cy + dy;
      if (x < 0 || y < 0 || x >= grid.length || y >= grid.length) continue;
      const d = Math.max(Math.abs(dx - 3), Math.abs(dy - 3));
      grid[y][x] = d !== 2 && d <= 3;
    }
  }
}

function placeFunctionPatterns(grid: Grid, version: number): void {
  const size = grid.length;
  placeFinder(grid, 0, 0);
  placeFinder(grid, size - 7, 0);
  placeFinder(grid, 0, size - 7);

  // Timing patterns, row and column 6.
  for (let i = 8; i < size - 8; i++) {
    const dark = i % 2 === 0;
    if (grid[6][i] === null) grid[6][i] = dark;
    if (grid[i][6] === null) grid[i][6] = dark;
  }

  // Alignment patterns at every centre pair except the three finder corners.
  //
  // "Except the corners" is an *index* rule, not "except where something is already
  // written": from version 7 the centres include one on the timing column, and
  // skipping it because the cell was occupied dropped a real alignment pattern —
  // which shifts every subsequent data module and produces a symbol no scanner
  // reads. Versions 2–6 hide the bug, because there the two rules coincide.
  const centres = VERSIONS[version - 1].align;
  const last = centres.length - 1;
  for (let i = 0; i <= last; i++) {
    for (let j = 0; j <= last; j++) {
      const corner =
        (i === 0 && j === 0) || (i === 0 && j === last) || (i === last && j === 0);
      if (corner) continue;
      const cy = centres[i];
      const cx = centres[j];
      for (let dy = -2; dy <= 2; dy++) {
        for (let dx = -2; dx <= 2; dx++) {
          grid[cy + dy][cx + dx] = Math.max(Math.abs(dx), Math.abs(dy)) !== 1;
        }
      }
    }
  }

  // Format-information area, reserved now and written after masking. Placeholder
  // `false` rather than `null` so the data walk skips these cells.
  for (let i = 0; i < 9; i++) {
    if (grid[8][i] === null) grid[8][i] = false;
    if (grid[i][8] === null) grid[i][8] = false;
  }
  for (let i = 0; i < 8; i++) {
    grid[8][size - 1 - i] = false;
    grid[size - 1 - i][8] = false;
  }
  // The dark module: fixed, and not part of the format information.
  grid[size - 8][8] = true;

  if (version >= 7) {
    const bits = versionInfoBits(version);
    for (let i = 0; i < 18; i++) {
      const bit = ((bits >>> i) & 1) === 1;
      grid[Math.floor(i / 3)][size - 11 + (i % 3)] = bit;
      grid[size - 11 + (i % 3)][Math.floor(i / 3)] = bit;
    }
  }
}

/** BCH(18,6) version information, for version 7 and up. */
function versionInfoBits(version: number): number {
  let rem = version;
  for (let i = 0; i < 12; i++) {
    rem = (rem << 1) ^ ((rem >>> 11) * 0x1f25);
  }
  return ((version << 12) | rem) >>> 0;
}

/** BCH(15,5) format information for error level M and the given mask. */
function formatInfoBits(mask: number): number {
  const data = (ECC_BITS_M << 3) | mask;
  let rem = data;
  for (let i = 0; i < 10; i++) {
    rem = (rem << 1) ^ ((rem >>> 9) * 0x537);
  }
  // The XOR is what stops an all-zero format field (level M, mask 0) from looking
  // like an unwritten symbol.
  return (((data << 10) | rem) ^ 0x5412) >>> 0;
}

/** Walk the two-module-wide serpentine, writing every codeword bit. */
function placeData(grid: Grid, codewords: Uint8Array): void {
  const size = grid.length;
  let bit = 0;
  let upward = true;
  for (let right = size - 1; right >= 1; right -= 2) {
    // Column 6 is the vertical timing pattern; the pairs jog left around it.
    const cols = right === 6 ? [5, 4] : [right, right - 1];
    for (let step = 0; step < size; step++) {
      const y = upward ? size - 1 - step : step;
      for (const x of cols) {
        if (grid[y][x] !== null) continue;
        const byte = codewords[bit >>> 3];
        // Past the end of the stream the remaining modules stay light: the spec's
        // remainder bits, which exist for versions whose module count is not a
        // multiple of 8.
        grid[y][x] = byte !== undefined && ((byte >>> (7 - (bit & 7))) & 1) === 1;
        bit++;
      }
    }
    upward = !upward;
    if (right === 6) right -= 1; // the jog consumed the extra column
  }
}

/** Whether mask `m` inverts the module at (x, y). */
function maskAt(m: number, x: number, y: number): boolean {
  switch (m) {
    case 0: return (x + y) % 2 === 0;
    case 1: return y % 2 === 0;
    case 2: return x % 3 === 0;
    case 3: return (x + y) % 3 === 0;
    case 4: return (Math.floor(y / 2) + Math.floor(x / 3)) % 2 === 0;
    case 5: return ((x * y) % 2) + ((x * y) % 3) === 0;
    case 6: return (((x * y) % 2) + ((x * y) % 3)) % 2 === 0;
    default: return (((x + y) % 2) + ((x * y) % 3)) % 2 === 0;
  }
}

/**
 * The four penalty rules, summed.
 *
 * Implemented straight from the spec rather than cleverly: this runs eight times
 * for a symbol of at most 57×57, once, in a popover.
 */
function penalty(m: boolean[][]): number {
  const size = m.length;
  let score = 0;

  // Rule 1: runs of five or more same-colour modules in a row or column.
  for (let i = 0; i < size; i++) {
    for (const line of [m[i], m.map((row) => row[i])]) {
      let run = 1;
      for (let j = 1; j < size; j++) {
        if (line[j] === line[j - 1]) {
          run++;
          if (run === 5) score += 3;
          else if (run > 5) score += 1;
        } else {
          run = 1;
        }
      }
    }
  }

  // Rule 2: every 2×2 block of one colour.
  for (let y = 0; y < size - 1; y++) {
    for (let x = 0; x < size - 1; x++) {
      const v = m[y][x];
      if (v === m[y][x + 1] && v === m[y + 1][x] && v === m[y + 1][x + 1]) score += 3;
    }
  }

  // Rule 3: the finder-lookalike 1:1:3:1:1 pattern with four light modules on
  // either side, in either orientation.
  const P1 = [true, false, true, true, true, false, true, false, false, false, false];
  const P2 = [false, false, false, false, true, false, true, true, true, false, true];
  const matches = (line: boolean[], at: number, pat: boolean[]) =>
    pat.every((v, k) => line[at + k] === v);
  for (let i = 0; i < size; i++) {
    const row = m[i];
    const col = m.map((r) => r[i]);
    for (let j = 0; j + 11 <= size; j++) {
      for (const line of [row, col]) {
        if (matches(line, j, P1)) score += 40;
        if (matches(line, j, P2)) score += 40;
      }
    }
  }

  // Rule 4: deviation from an even dark/light split.
  let dark = 0;
  for (const row of m) for (const v of row) if (v) dark++;
  const percent = (dark * 100) / (size * size);
  score += Math.floor(Math.abs(percent - 50) / 5) * 10;

  return score;
}

function writeFormatInfo(m: boolean[][], mask: number): void {
  const size = m.length;
  const bits = formatInfoBits(mask);
  const bit = (i: number) => ((bits >>> i) & 1) === 1;
  // The field is written twice, in the two placements the spec gives — a symbol
  // whose top-left corner is damaged is still readable from the other copy.
  //
  // Indexing is `modules[y][x]` and the spec's own diagrams are (column, row), so
  // every line here is a transposition waiting to happen: the first version of this
  // function had all six of them the wrong way round, which produces a symbol that
  // looks completely normal and decodes as nothing.
  for (let i = 0; i <= 5; i++) m[i][8] = bit(i);
  m[7][8] = bit(6);
  m[8][8] = bit(7);
  m[8][7] = bit(8);
  for (let i = 9; i <= 14; i++) m[8][14 - i] = bit(i);

  for (let i = 0; i <= 7; i++) m[8][size - 1 - i] = bit(i);
  for (let i = 8; i <= 14; i++) m[size - 15 + i][8] = bit(i);
}

/**
 * Encode `text` as a QR symbol, or `null` when it does not fit versions 1–10.
 *
 * The mask is chosen by the spec's penalty evaluation over all eight candidates,
 * not fixed: a payload that happens to produce a finder-lookalike run inside the
 * data area is exactly the case a fixed mask gets wrong, and it would be
 * unreproducible from a bug report.
 */
export function encodeQr(text: string, forceMask?: number): QrMatrix | null {
  const bytes = new TextEncoder().encode(text);
  const version = MAX_BYTES_M.findIndex((max) => bytes.length <= max) + 1;
  if (version === 0) return null;

  const codewords = interleave(dataCodewords(bytes, version), version);
  const size = 17 + 4 * version;
  const grid = blankGrid(size);
  placeFunctionPatterns(grid, version);
  // Which cells the mask applies to: everything the data walk was allowed to fill.
  const isData = grid.map((row) => row.map((v) => v === null));
  placeData(grid, codewords);
  const base = grid.map((row) => row.map((v) => v === true));

  let best: boolean[][] | null = null;
  let bestScore = Infinity;
  let bestMask = 0;
  for (let mask = forceMask ?? 0; mask < 8; mask++) {
    const candidate = base.map((row, y) =>
      row.map((v, x) => (isData[y][x] && maskAt(mask, x, y) ? !v : v)),
    );
    writeFormatInfo(candidate, mask);
    const score = penalty(candidate);
    if (score < bestScore) {
      bestScore = score;
      best = candidate;
      bestMask = mask;
    }
    if (forceMask !== undefined) break;
  }
  // `best` is always set — the loop runs eight times — but the compiler does not
  // know that and a non-null assertion here would be the one place this file lies.
  if (!best) return null;
  writeFormatInfo(best, bestMask);
  return { version, size, modules: best };
}

/**
 * The dark modules as one SVG path, in a viewBox of `size + 2 * quiet` units.
 *
 * One path rather than a rect per module: a version-10 symbol is 2916 modules and
 * roughly half of them are dark, which is 1400 DOM nodes for a popover. A path also
 * scales with `width`/`height` alone, so the caller picks a size without the
 * renderer knowing anything about it.
 *
 * The quiet zone is not decoration — a scanner needs the light border to find the
 * symbol at all, and four modules is the spec's minimum.
 */
export const QR_QUIET_ZONE = 4;

/**
 * The quiet zone drawn *inside the SVG* on screen.
 *
 * Two rather than four, and that is not a spec violation: the quiet zone is a
 * requirement about the light margin around the symbol, not about how much of that
 * margin lives inside the image. On screen the code sits on a white card inside a
 * padded row, so the light area continues well past the SVG's edge — where a
 * four-module border inside the image only made the code look framed.
 *
 * The **copied PNG keeps the full four** ([`QR_QUIET_ZONE`]), because a picture pasted
 * into a chat has no card around it: whatever the message background is starts at the
 * image edge.
 */
export const QR_SCREEN_QUIET_ZONE = 2;

/**
 * The veld mark, as the data both renderers need to draw it at a symbol's centre.
 *
 * Lives here — beside the encoder, in the module with no DOM dependency — because
 * *two* renderers draw it: the SVG on screen and the canvas that produces the PNG for
 * the clipboard. They must agree, or the code someone pastes into Slack is not the code
 * they were looking at when they pressed the button.
 *
 * `fraction` is an **error-correction budget**. Level M recovers ~15% of the
 * codewords, and everything the mark covers is damage the decoder has to repair. At
 * 18% of the side the mark hides ~3.2% of the area, which is comfortably inside that
 * budget and about what a commercial logo-QR generator uses at this level. Raising it
 * is not free: past roughly 7% of the area, codes begin failing on cheap scanners, and
 * they fail *intermittently* — the worst way for this to be wrong.
 *
 * The centre of a symbol is always data or an alignment pattern, never a finder, so a
 * mark this size cannot damage the structures a decoder uses to *locate* the code —
 * only payload it can rebuild.
 *
 * Path data is `logo.svg` verbatim (a 32×32 viewBox), drawn **entirely in the module
 * colour** — the `V` instead of the file's white, since here it sits on a white plate,
 * and the dot instead of the accent green. Losing the green costs the mark its one
 * colour, and buys the thing that matters more: a decoder classifies every cell as
 * light or dark, and `#C4F56A` on white is a light cell sitting where dark modules
 * belong. All-black keeps the mark reading as damage the error correction repairs,
 * rather than as a patch of *plausible* light modules for a scanner to misread. It is
 * also the one place in the app where the brand's accent is deliberately dropped, which
 * is why it is written down here rather than looking like an oversight.
 */
export const VELD_MARK = {
  /** Mark side as a fraction of the symbol side (quiet zone included). */
  fraction: 0.18,
  /** Inset of the glyph inside its white plate, in modules. */
  pad: 0.6,
  /** Smallest mark side in modules, so it stays legible on a version-1 symbol. */
  minSide: 5,
  /** The source viewBox the two path strings are drawn in. */
  viewBox: 32,
  glyph: "M13.2 28L4 4H8.4L15.7 23.8H15.8L23.1 4H27.5L18.3 28H13.2Z",
  dot: "M24.5 29C25.8807 29 27 27.8807 27 26.5C27 25.1193 25.8807 24 24.5 24C23.1193 24 22 25.1193 22 26.5C22 27.8807 23.1193 29 24.5 29Z",
  /** Black, not the accent green — see the note above. */
  dotFill: "#000000",
} as const;

/** The mark's side and origin for a symbol whose viewBox is `box` modules. */
export function veldMarkBox(box: number): { side: number; origin: number } {
  const side = Math.max(VELD_MARK.minSide, Math.round(box * VELD_MARK.fraction));
  return { side, origin: (box - side) / 2 };
}

export function qrPath(qr: QrMatrix, quiet: number = QR_QUIET_ZONE): string {
  const parts: string[] = [];
  for (let y = 0; y < qr.size; y++) {
    for (let x = 0; x < qr.size; x++) {
      if (!qr.modules[y][x]) continue;
      // Runs are merged horizontally: the same pixels, ~40% fewer path commands.
      let run = 1;
      while (x + run < qr.size && qr.modules[y][x + run]) run++;
      parts.push(`M${x + quiet} ${y + quiet}h${run}v1h-${run}z`);
      x += run - 1;
    }
  }
  return parts.join("");
}

/**
 * CSS pixels per module, at minimum.
 *
 * **Three, and measured rather than chosen.** Every symbol this encoder produces was
 * rendered at 2, 3, 4, 6 and 8 device pixels per module and decoded with OpenCV's
 * `QRCodeDetector` — plain, and with a solid black square covering the whole centre-mark
 * footprint (strictly more damage than the real glyph). At 3 and above everything
 * decoded. **At 2 the version-2 symbol with the mark did not.**
 *
 * Two lives on a Retina display, where a CSS pixel is two device pixels — which is why
 * the first version of this looked fine. It is a DPR-1 external monitor that breaks it,
 * and "works on the laptop screen, sometimes fails on the desk monitor" is the worst
 * shape this bug could have taken.
 *
 * The cost is real and accepted: a long payload now renders larger than the target below
 * asks for (a 213-byte link is ~195px rather than ~130px). A code that is bigger than
 * intended is a cosmetic complaint; a code that does not scan is the feature not
 * working.
 */
const MIN_MODULE_PX = 3;

/**
 * The rendered side for a symbol: an **integer** number of pixels per module.
 *
 * A fractional scale is the thing to avoid. `viewBox` units are modules, so a 45-unit
 * symbol drawn into 112px puts module edges on 2.489-pixel boundaries; the browser
 * then anti-aliases every edge into grey, which is exactly the contrast a scanner is
 * looking for. Snapping to an integer scale means every module is a whole number of
 * pixels and the edges stay hard.
 *
 * Picks the largest integer scale that fits `target`, with `MIN_MODULE_PX` as a floor
 * that wins over the target — a version-10 symbol is 65 units wide and would
 * otherwise be asked to render at 1px a module.
 */
export function qrRenderSize(boxUnits: number, target: number): number {
  const scale = Math.max(MIN_MODULE_PX, Math.floor(target / boxUnits));
  return boxUnits * scale;
}

/** Side of the SVG viewBox for `qr`, in module units, quiet zone included. */
export function qrViewBox(qr: QrMatrix, quiet: number = QR_QUIET_ZONE): number {
  return qr.size + 2 * quiet;
}
